### ISSUE TITLE
external function getValue not exist

### ISSUE THREAD

**Issue by l123173** [epics-extensions/CALab#23]
Hi ,
    I have a program using calab. Both vi and exe run well in my pc.
   Recentallly, I copy the program to other pc, and the vi run well in this pc.
   But the following error came out, when i make the program to exe.

In VI CaLab.lvlib:CaLabGet_Main.vi did not exist external function calab.dll:getValue:C.
In VI CaLab.lvlib:CaLabPut_Main.vi did not exist external function calab.dll:getValue:C.

    i tried to mass compile , tried to make it to exe program again, tried to reinstall calab, and check all the dependency in labview.
    the vi did run well, and the exe always said the error.
  
  Could you give me some suggestion.

**Comment by nugatritter** [comment]
Did you check "[CA Lab VIs aren't executable, what can I do? (Windows®)](https://helmholtz-berlin.de/zentrum/organisation/it/calab/faq_en.html#c458636 FAQ)"?

**Comment by l123173** [comment]
Hi，

      It was solved already.  I check the problem in the last two days. 

      And the reason was location of calab dll. 

 

     I used old version of calab when i write the  program, the dll location was:  labview user.lib/

     now we changed the pc and calab dll was in xxxx/Roman/calab.

     When i used the old program, the error came out.




     click the give option and give it new dll location in caGet and caPut vi, the make exe could solve the problem.




Thanks for your reply.

Regards,

liang

     













At 2024-11-18 15:42:05, "Carsten Winkler" ***@***.***> wrote:

Did you check "[CA Lab VIs aren't executable, what can I do? (Windows®)](https://helmholtz-berlin.de/zentrum/organisation/it/calab/faq_en.html#c458636 FAQ)"?
